#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

settingsfile=$OPENSHIFT_REPO_DIR/settings.json

if [[ -f $settingsfile ]]
then
  rm $settingsfile
fi

cp $OPENSHIFT_REPO_DIR/settings.json.template $OPENSHIFT_REPO_DIR/settings.json

sed -i 's/OPENSHIFT_NODEJS_IP/'$OPENSHIFT_NODEJS_IP'/' $settingsfile
sed -i 's/OPENSHIFT_NODEJS_PORT/'$OPENSHIFT_NODEJS_PORT'/' $settingsfile
sed -i 's/OPENSHIFT_MONGODB_DB_USERNAME/'$OPENSHIFT_MONGODB_DB_USERNAME'/' $settingsfile
sed -i 's/OPENSHIFT_MONGODB_DB_HOST/'$OPENSHIFT_MONGODB_DB_HOST'/' $settingsfile
sed -i 's/OPENSHIFT_MONGODB_DB_PORT/'$OPENSHIFT_MONGODB_DB_PORT'/' $settingsfile
sed -i 's/OPENSHIFT_MONGODB_DB_PASSWORD/'$OPENSHIFT_MONGODB_DB_PASSWORD'/' $settingsfile
sed -i 's/OPENSHIFT_APP_NAME/'$OPENSHIFT_APP_NAME'/' $settingsfile

#make sure the etherpad deps are installed
pushd $OPENSHIFT_REPO_DIR/node_modules
if [[ -f ./ep_etherpad-lite ]]
then
  rm ep_etherpad-lite
fi
ln -s ../src/ ep_etherpad-lite
cd ep_etherpad-lite
npm install
popd
