#!/bin/bash
# This is a simple build script and will be executed on your CI system if
# available.  Otherwise it will execute while your application is stopped
# before the deploy step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

#Link the project
if [[ ! -d $OPENSHIFT_REPO_DIR/node_modules ]]
then
  mkdir $OPENSHIFT_REPO_DIR/node_modules
fi
pushd $OPENSHIFT_REPO_DIR/node_modules
if [[ -f ./ep_etherpad-lite ]]
then
  rm ep_etherpad-lite
fi
ln -s ../src/ ep_etherpad-lite
popd
